- Instantaneous Demand:
    url: '/upt/1/mr/1/r'
    tags:
      value:
        entity_type: sensor
        device_class: power
        unit_of_measurement: W
        state_class: measurement
        enabled_by_default: true
      qualityFlags:
        entity_type: sensor
        state_class: measurement
        enabled_by_default: false
      timePeriod:
        - duration:
            entity_type: sensor
            device_class: duration
            value_template: '{{ value }}'
            unit_of_measurement: s
        - start:
            entity_type: sensor
            device_class: timestamp
            value_template: '{{ as_datetime( value ) }}'

- Current Summation Received:
    url: '/upt/1/mr/2/rs/1/r/1'
    tags:
      timePeriod:
        - duration:
            entity_type: sensor
            device_class: duration
            value_template: '{{ value }}'
            unit_of_measurement: s
        - start:
            entity_type: sensor
            device_class: timestamp
            value_template: '{{ as_datetime( value ) }}'
      touTier:
        entity_type: sensor
      value:
        entity_type: sensor
        device_class: energy
        unit_of_measurement: Wh
        state_class: total
        enabled_by_default: true
      qualityFlags:
        entity_type: sensor
        state_class: measurement
        enabled_by_default: false

- Current Summation Delivered:
    url: '/upt/1/mr/3/rs/1/r/1'
    tags:
      timePeriod:
        - duration:
            entity_type: sensor
            device_class: duration
            value_template: '{{ value }}'
            unit_of_measurement: s
        - start:
            entity_type: sensor
            device_class: timestamp
            value_template: '{{ as_datetime( value ) }}'
      touTier:
        entity_type: sensor
      value:
        entity_type: sensor
        device_class: energy
        unit_of_measurement: Wh
        state_class: total
        enabled_by_default: true
      qualityFlags:
        entity_type: sensor
        state_class: measurement
        enabled_by_default: false

- VAh Received:
    url: '/upt/1/mr/4/r'
    tags:
      value:
        entity_type: sensor
        device_class: energy
        unit_of_measurement: VAh
        state_class: total
        enabled_by_default: false
      qualityFlags:
        entity_type: sensor
        state_class: measurement
        enabled_by_default: false
      timePeriod:
        - duration:
            entity_type: sensor
            device_class: duration
            value_template: '{{ value }}'
            unit_of_measurement: s
        - start:
            entity_type: sensor
            device_class: timestamp
            value_template: '{{ as_datetime( value ) }}'

- VAh Delivered:
    url: '/upt/1/mr/5/r'
    tags:
      value:
        entity_type: sensor
        device_class: energy
        unit_of_measurement: VAh
        state_class: total
        enabled_by_default: false
      qualityFlags:
        entity_type: sensor
        state_class: measurement
        enabled_by_default: false
      timePeriod:
        - duration:
            entity_type: sensor
            device_class: duration
            value_template: '{{ value }}'
            unit_of_measurement: s
        - start:
            entity_type: sensor
            device_class: timestamp
            value_template: '{{ as_datetime( value ) }}'

- VARh Received:
    url: '/upt/1/mr/6/r'
    tags:
      value:
        entity_type: sensor
        device_class: energy
        unit_of_measurement: VARh
        state_class: total
        enabled_by_default: false
      qualityFlags:
        entity_type: sensor
        state_class: measurement
        enabled_by_default: false
      timePeriod:
        - duration:
            entity_type: sensor
            device_class: duration
            value_template: '{{ value }}'
            unit_of_measurement: s
        - start:
            entity_type: sensor
            device_class: timestamp
            value_template: '{{ as_datetime( value ) }}'

- VARh Delivered:
    url: '/upt/1/mr/7/r'
    tags:
      value:
        entity_type: sensor
        device_class: energy
        unit_of_measurement: VARh
        state_class: total
        enabled_by_default: false
      qualityFlags:
        entity_type: sensor
        state_class: measurement
        enabled_by_default: false
      timePeriod:
        - duration:
            entity_type: sensor
            device_class: duration
            value_template: '{{ value }}'
            unit_of_measurement: s
        - start:
            entity_type: sensor
            device_class: timestamp
            value_template: '{{ as_datetime( value ) }}'

- TOU WH Received:
    url: '/upt/1/mr/8/rs/1/r/1'
    tags:
      value:
        entity_type: sensor
        device_class: energy
        unit_of_measurement: Wh
        state_class: total
        enabled_by_default: true
      qualityFlags:
        entity_type: sensor
        state_class: measurement
        enabled_by_default: false
      timePeriod:
        - duration:
            entity_type: sensor
            device_class: duration
            value_template: '{{ value }}'
            unit_of_measurement: s
        - start:
            entity_type: sensor
            device_class: timestamp
            value_template: '{{ as_datetime( value ) }}'
      touTier:
        entity_type: sensor

- TOU WH Delivered:
    url: '/upt/1/mr/9/rs/1/r/1'
    tags:
      value:
        entity_type: sensor
        device_class: energy
        unit_of_measurement: Wh
        state_class: total
        enabled_by_default: true
      qualityFlags:
        entity_type: sensor
        state_class: measurement
        enabled_by_default: false
      timePeriod:
        - duration:
            entity_type: sensor
            device_class: duration
            value_template: '{{ value }}'
            unit_of_measurement: s
        - start:
            entity_type: sensor
            device_class: timestamp
            value_template: '{{ as_datetime( value ) }}'
      touTier:
        entity_type: sensor

- Max Demand Received:
    url: '/upt/1/mr/17/r'
    tags:
      value:
        entity_type: sensor
        device_class: power
        unit_of_measurement: W
        state_class: measurement
        enabled_by_default: true
      qualityFlags:
        entity_type: sensor
        state_class: measurement
        enabled_by_default: false
      timePeriod:
        - duration:
            entity_type: sensor
            device_class: duration
            value_template: '{{ value }}'
            unit_of_measurement: s
        - start:
            entity_type: sensor
            device_class: timestamp
            value_template: '{{ as_datetime( value ) }}'

- Max Demand Delivered:
    url: '/upt/1/mr/18/r'
    tags:
      value:
        entity_type: sensor
        device_class: power
        unit_of_measurement: W
        state_class: measurement
        enabled_by_default: true
      qualityFlags:
        entity_type: sensor
        state_class: measurement
        enabled_by_default: false
      timePeriod:
        - duration:
            entity_type: sensor
            device_class: duration
            value_template: '{{ value }}'
            unit_of_measurement: s
        - start:
            entity_type: sensor
            device_class: timestamp
            value_template: '{{ as_datetime( value ) }}'

- Power Factor:
    url: '/upt/1/mr/19/r'
    tags:
      value:
        entity_type: sensor
        device_class: power_factor
        unit_of_measurement: ''
        state_class: measurement
        value_template: '{{ value | float / 1000 }}'
        enabled_by_default: true
      qualityFlags:
        entity_type: sensor
        state_class: measurement
        enabled_by_default: false
      timePeriod:
        - duration:
            entity_type: sensor
            device_class: duration
            value_template: '{{ value }}'
            unit_of_measurement: s
        - start:
            entity_type: sensor
            device_class: timestamp
            value_template: '{{ as_datetime( value ) }}'

- Power Factor PhaseA:
    url: '/upt/1/mr/20/r'
    tags:
      value:
        entity_type: sensor
        device_class: power_factor
        unit_of_measurement: ''
        state_class: measurement
        value_template: '{{ value | float / 1000 if value else None }}'
        enabled_by_default: false
      qualityFlags:
        entity_type: sensor
        state_class: measurement
        enabled_by_default: false
      timePeriod:
        - duration:
            entity_type: sensor
            device_class: duration
            value_template: '{{ value }}'
            unit_of_measurement: s
        - start:
            entity_type: sensor
            device_class: timestamp
            value_template: '{{ as_datetime( value ) }}'

- Power Factor PhaseB:
    url: '/upt/1/mr/21/r'
    tags:
      value:
        entity_type: sensor
        device_class: power_factor
        unit_of_measurement: ''
        state_class: measurement
        value_template: '{{ value | float / 1000 if value else None }}'
        enabled_by_default: false
      qualityFlags:
        entity_type: sensor
        state_class: measurement
        enabled_by_default: false
      timePeriod:
        - duration:
            entity_type: sensor
            device_class: duration
            value_template: '{{ value }}'
            unit_of_measurement: s
        - start:
            entity_type: sensor
            device_class: timestamp
            value_template: '{{ as_datetime( value ) }}'

- Power Factor PhaseC:
    url: '/upt/1/mr/22/r'
    tags:
      value:
        entity_type: sensor
        device_class: power_factor
        unit_of_measurement: ''
        state_class: measurement
        value_template: '{{ value | float / 1000 if value else None }}'
        enabled_by_default: false
      qualityFlags:
        entity_type: sensor
        state_class: measurement
        enabled_by_default: false
      timePeriod:
        - duration:
            entity_type: sensor
            device_class: duration
            value_template: '{{ value }}'
            unit_of_measurement: s
        - start:
            entity_type: sensor
            device_class: timestamp
            value_template: '{{ as_datetime( value ) }}'
