services:
  xcel_itron2mqtt:
    image: ghcr.io/nils154/xcel_itron2mqtt:main
    restart: unless-stopped
    network_mode: host
    container_name: xcel_itron2mqtt
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /srv/docker/xcel/certs:/opt/xcel_itron2mqtt/certs
    environment:
      MQTT_SERVER: 
      MQTT_PORT: 
      MQTT_USER: 
      MQTT_PASSWORD: 
      METER_PORT: 
